### ISSUE TITLE
Plugin not opening on linux

### ISSUE THREAD

**Issue by ajgwords** [EO-DataHub/eodh-qgis#2]
Installing using the v0.0.1 zip file throws this error when using QGIS 3.38 on Pop_OS Linux.
The installation seems to work - the error comes when trying to open the plugin.

2024-10-24T16:25:28     WARNING    Traceback (most recent call last):
              File "/home/al/.local/share/QGIS/QGIS3/profiles/default/python/plugins/eodh_qgis/main.py", line 163, in run
              self.dlg = MainDialog()
              File "/home/al/.local/share/QGIS/QGIS3/profiles/default/python/plugins/eodh_qgis/gui/main_dialog.py", line 41, in __init__
              "widget": SettingsWidget(parent=self),
              File "/home/al/.local/share/QGIS/QGIS3/profiles/default/python/plugins/eodh_qgis/gui/settings_widget.py", line 34, in __init__
              self.check_updates_on_start.setChecked(self.settings.data["check_update"])
             TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'

**Comment by figi44** [comment]
Fixed in ce4e70a, will be released in 0.0.2
